// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return _android;
      case TargetPlatform.iOS:
        return _ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions _android = FirebaseOptions(
    apiKey: 'AIzaSyC1rKu9ufl5gLXqWksZ-lkhCM3NsNgQjmM',
    appId: '1:883165791671:android:6dd739ab9f6de64547d432',
    messagingSenderId: '883165791671',
    projectId: 'kambaiiwellnessapp',
    storageBucket: 'kambaiiwellnessapp.firebasestorage.app',
  );

  static const FirebaseOptions _ios = FirebaseOptions(
    apiKey: 'AIzaSyCzzPjtoh7sOCtpA5wBCMZtkO4ahgrYlt4',
    appId: '1:883165791671:ios:4766f4c9d3e1e1c647d432',
    messagingSenderId: '883165791671',
    projectId: 'kambaiiwellnessapp',
    storageBucket: 'kambaiiwellnessapp.firebasestorage.app',
    iosClientId: '883165791671-8i7u3sg62vff1mjej0lau9ffb3ckj63a.apps.googleusercontent.com',
    iosBundleId: 'com.kambaii.kambaiihealth',
  );
}
